In [1]:
# Dependencies
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
# Import vine table csv into a dataframe
vine_table = pd.read_csv("../Module17/vine_table.csv")
vine_table.head()

review_id  star_rating  helpful_votes  total_votes vine  \
0  R1WBPB8MDCCN8F          5.0            0.0          0.0    N   
1  R32M0YEWV77XG8          5.0            1.0          1.0    N   
2   RR8V7WR27NXJ5          1.0            0.0          0.0    N   
3  R1MHO5V9Z932AY          5.0            0.0          0.0    N   
4  R16PD71086BD2V          5.0            0.0          1.0    N   

  verified_purchase  
0                 N  
1                 Y  
2                 Y  
3                 Y  
4                 N

In [3]:
vine_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4850360 entries, 0 to 4850359
Data columns (total 6 columns):
 #   Column             Dtype  
---  ------             -----  
 0   review_id          object 
 1   star_rating        float64
 2   helpful_votes      float64
 3   total_votes        float64
 4   vine               object 
 5   verified_purchase  object 
dtypes: float64(3), object(3)
memory usage: 222.0+ MB


In [4]:
# 2.1 Create a new DataFrame or table to retrieve all the rows where the total_votes count is equal to or greater than 20.
# To pick reviews that are more likely to be helpful and to avoid having division by zero errors later on
total_votes_greater = vine_table[vine_table['total_votes'] >= 20]
total_votes_greater.head()

review_id  star_rating  helpful_votes  total_votes vine  \
326   R1B4753QMTD8ON          5.0           32.0         32.0    N   
662   R28BVHOEL6GCHZ          5.0           21.0         21.0    N   
1055  R27IB4BRKO71I0          2.0           16.0         20.0    N   
1225   RJ86OW12Y4NRL          5.0          124.0        128.0    N   
1448  R3KRABOWCH6ZE4          1.0           48.0         65.0    N   

     verified_purchase  
326                  N  
662                  Y  
1055                 Y  
1225                 Y  
1448                 Y

In [5]:
# 2.2 Create a new DataFrame to retrieve all the rows where the number of helpful votes divided by total votes is equal to or greater than 50%
divided_vine_table = total_votes_greater.loc[total_votes_greater.helpful_votes/total_votes_greater.total_votes >=0.5]
divided_vine_table.head()

review_id  star_rating  helpful_votes  total_votes vine  \
326   R1B4753QMTD8ON          5.0           32.0         32.0    N   
662   R28BVHOEL6GCHZ          5.0           21.0         21.0    N   
1055  R27IB4BRKO71I0          2.0           16.0         20.0    N   
1225   RJ86OW12Y4NRL          5.0          124.0        128.0    N   
1448  R3KRABOWCH6ZE4          1.0           48.0         65.0    N   

     verified_purchase  
326                  N  
662                  Y  
1055                 Y  
1225                 Y  
1448                 Y

In [6]:
# 2.3 Create a new DF that retrieves all the rows where a review was written as part of Vine program (paid), vine == 'Y'
yes_vine = divided_vine_table[divided_vine_table['vine'] == 'Y']
yes_vine.head()

review_id  star_rating  helpful_votes  total_votes vine  \
5506    R32OMS1LSDRCOB          4.0           27.0         31.0    Y   
24578   R2IPKK4I0XRCFR          4.0           16.0         21.0    Y   
58364    RXYYJ8SGI9IX6          5.0           36.0         41.0    Y   
63194   R1SAUBFC7T6JHC          5.0           73.0         75.0    Y   
177724  R329HVJKKHWSG3          5.0           59.0         59.0    Y   

       verified_purchase  
5506                   N  
24578                  N  
58364                  N  
63194                  N  
177724                 N

In [7]:
# 2.4 Repeat step 3, but for Vine program (unpaid), vine == 'N'
no_vine = divided_vine_table[divided_vine_table['vine'] == 'N']
no_vine.head()

review_id  star_rating  helpful_votes  total_votes vine  \
326   R1B4753QMTD8ON          5.0           32.0         32.0    N   
662   R28BVHOEL6GCHZ          5.0           21.0         21.0    N   
1055  R27IB4BRKO71I0          2.0           16.0         20.0    N   
1225   RJ86OW12Y4NRL          5.0          124.0        128.0    N   
1448  R3KRABOWCH6ZE4          1.0           48.0         65.0    N   

     verified_purchase  
326                  N  
662                  Y  
1055                 Y  
1225                 Y  
1448                 Y

In [15]:
# STEP 5: Determine the total number of reviews, the number of 5-star reviews, and the percentage of 5-star reviews for the two types of review (paid vs unpaid)
# 5.1 total number of reviews (paid)
paid_reviews = len(yes_vine)
paid_reviews

334

In [16]:
# total number of reviews (unpaid)
unpaid_reviews = len(no_vine)
unpaid_reviews

61614

334 paid vine reviews and 61,614 unpaid vine reviews

In [12]:
# 5.2 number of 5-star reviews (paid)
paid_max_review = len(yes_vine[yes_vine['star_rating'] == 5])
paid_max_review

139

In [13]:
# number of 5-star reviews (unpaid)
unpaid_max_review = len(no_vine[no_vine['star_rating'] == 5])
unpaid_max_review

32665

139 paid 5-star reviews and 32,665 unpaid 5-star reviews

In [17]:
# 5.3 Percentage of 5-star reviews of paid
paid_max_review/paid_reviews

0.4161676646706587

In [18]:
# unpaid percentage
unpaid_max_review/unpaid_reviews

0.5301554841432142